Update README.md
datarobot-community/examples-for-data-scientists pull request #8
Opened 2022-02-08 19:11 UTC by nate-goudreault

Adding resource locations to the readme

2022-02-08 19:19 UTC, lindahaviland commented on README.md
> +- [Tutorials for data scientists repo](https://github.com/datarobot-community/tutorials-for-data-scientists/)
this is also listed under "Important Links" - guessing you should remove that other link

2022-02-08 19:26 UTC, lindahaviland commented on README.md
> +
Additional changes under Important Links:

- To learn how to use DataRobot and gain practical data science education, visit [DataRobot University](https://university.datarobot.com/).
-  To ask questions and get help from DataRobot experts and peers, visit [DataRobot Community](https://community.datarobot.com/t5/datarobot-community/ct-p/en).

2022-02-08 19:28 UTC, lindahaviland requested changes
couple of small things. Guessing you want to remove the link to the repo since it's now in your new list. thank you!

2022-02-10 16:14 UTC, nate-goudreault commented
@lindahaviland this and the other two PRs are fixed and ready for review

https://github.com/datarobot-community/ai_engineering/pull/43

https://github.com/datarobot-community/tutorials-for-data-scientists/pull/9

2022-02-14 17:44 UTC, lindahaviland approved these changes
Looks good, thank you.
 Future: Just noticed we'll want to change the https://github.com/datarobot-community/examples-for-data-scientists/blob/0ab50428ae2822cd5732cd8b838d57bbcb93166f/CONTRIBUTING.md and https://github.com/datarobot-community/examples-for-data-scientists/blob/0ab50428ae2822cd5732cd8b838d57bbcb93166f/CODE_OF_CONDUCT.md pages, but not part of this ticket. These are linked from all readmes (or almost all) and are out-of-date.

2022-02-15 14:44 UTC, merged